server:
  port: 9000

spring:
  profiles:
    active: local

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# log 설정
logging:
  config: classpath:logback-spring.xml
  file:
    path: logs/

# AWS EC2 MetadataUtils Error 처리
spring.autoconfigure.exclude: org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration


