server:
  port: 9090

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

# log 설정
logging:
  config: classpath:spring-logback.xml
  file:
    path: logs/

# AWS EC2 MetadataUtils Error 처리
spring.autoconfigure.exclude: org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration





